spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
  mvc:
    static-path-pattern: /static/**
  session:
    timeout: -1
  pid:
    file: boot.pid
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

